solr_assocs:
  url: "http://browser.planteome.org/solr"
  timeout: 5
amigo_solr_assocs:
  url: "http://browser.planteome.org/solr"
  timeout: 8
solr_search:
  url: "http://browser.planteome.org/solr"
  timeout: 2
amigo_solr_search:
  url: "http://browser.planteome.org/solr"
  timeout: 2
sparql:
  url: "http://sparql.hegroup.org/sparql"
  timeout: 2
scigraph_ontology:
  url: "https://scigraph-ontology.monarchinitiative.org/scigraph/"
  timeout: 2
scigraph_data:
  url: "https://scigraph-ontology.monarchinitiative.org/scigraph/"
  timeout: 2
categories:
  - id: anatomy
    superclass: PO:0025131
  - id: phenotype
    superclass: TO:0000387
  - id: environment
    superclass: TO:0000387
default_solr_schema: amigo
ontologies:
  - id: magic1234
    handle: pato
    pre_load: true

